version: "3.8"

services:
  web_nginx:
    container_name: web_nginx
    image: nginx:stable-alpine
    volumes:
      - ${PORTAINER_PREFIXE}/${PORTAINER_DATA}/nginx/www:/usr/share/nginx/html
      - ${PORTAINER_PREFIXE}/${PORTAINER_DATA}/nginx/log:/var/log/nginx
      - ${PORTAINER_PREFIXE}/${PORTAINER_DATA}/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    labels:
      - traefik.enable=true
      - traefik.http.routers.nginx.rule=Path(`/nginx`)
    ports:
      - 8099:80
    restart: unless-stopped
    networks:
      - portainer_networks

  web_php:
    container_name: web_php
    #image: php:fpm-alpine
    # find Dockerfile ds le rep ${PORTAINER_PREFIXE}/${PORTAINER_DATA}/nginx
    build: '${PORTAINER_PREFIXE}/${PORTAINER_DATA}/nginx'
    volumes:
      - ${PORTAINER_PREFIXE}/${PORTAINER_DATA}/nginx/www:/script
      - ${PORTAINER_PREFIXE}/${PORTAINER_DATA}/nginx/php.ini:/usr/local/etc/php/php.ini
    networks:
      - portainer_networks


networks:
  portainer_networks:
    external: true
