version: "3.8"

services:
  sonarqube:
    container_name: sonarqube
    image: sonarqube:lts
    ports:
    - "9000:9000"
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://172.172.0.3:5432/sonarqube
      - SONARQUBE_JDBC_USERNAME=postgres
      - SONARQUBE_JDBC_PASSWORD=postgres
    volumes:
      - ${PORTAINER_PREFIXE}/${PORTAINER_DATA}/sonarqube/data:/opt/sonarqube/data
      #- ${PORTAINER_PREFIXE}/${PORTAINER_DATA}/sonarqube/conf:/opt/sonarqube/conf
      #- ${PORTAINER_PREFIXE}/${PORTAINER_DATA}/sonarqube/extensions:/opt/sonarqube/extensions
      #- ${PORTAINER_PREFIXE}/${PORTAINER_DATA}/sonarqube/bundled-plugins:/opt/sonarqube/lib/bundled-plugins
    labels:
      - traefik.enable=true
      - traefik.http.routers.sonarqube.rule=Path(`/sonarqube`)
    networks:
      - portainer_networks

networks:
  portainer_networks:
    external: true
