services:
  whoami:
    container_name: whoami
    # A container that exposes an API to show its IP address
    image: traefik/whoami:latest
    command:
       - --port=2001
    labels:
      - traefik.enable=true
      - traefik.http.routers.whoami.rule=Path(`/whoami`)
      #- traefik.http.routers.whoami.rule=Host(`whoami`) && PathPrefix(`/whoami`)