connection: mysql
host: mysql
user: statping
password: statping
database: statping
port: 3306
language: fr
allow_reports: true
location: /app
disable_http: false
demo_mode: false
disable_logs: false
use_assets: false
sample_data: false
use_cdn: false
disable_colors: false
